export const OPENWEATHER_API_KEY = "6d1569f544cff0b8b160fcb8bdcf7245";
export const WEATHERAPI_API_KEY = "ecf700bdb56546df9cc120424230106";

const weather = {
  current: {
    air_quality: {
      co: 260.4,
      "gb-defra-index": 1,
      no2: 18.7,
      o3: 89.4,
      pm10: 4.9,
      pm2_5: 4,
      so2: 5.1,
      "us-epa-index": 1,
    },
    cloud: 75,
    condition: {
      code: 1003,
      icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
      text: "Partly cloudy",
    },
    feelslike_c: 17,
    feelslike_f: 62.6,
    gust_kph: 22.3,
    gust_mph: 13.9,
    humidity: 23,
    is_day: 1,
    last_updated: "2024-04-06 16:15",
    last_updated_epoch: 1712409300,
    precip_in: 0,
    precip_mm: 0,
    pressure_in: 30.03,
    pressure_mb: 1017,
    temp_c: 17,
    temp_f: 62.6,
    uv: 5,
    vis_km: 10,
    vis_miles: 6,
    wind_degree: 90,
    wind_dir: "E",
    wind_kph: 15.1,
    wind_mph: 9.4,
  },
  forecast: { forecastday: [[Object], [Object], [Object]] },
  location: {
    country: "Turkey",
    lat: 39.93,
    localtime: "2024-04-06 16:24",
    localtime_epoch: 1712409871,
    lon: 32.86,
    name: "Ankara",
    region: "Ankara",
    tz_id: "Europe/Istanbul",
  },
};


const fore = [
  {
    astro: {
      is_moon_up: 0,
      is_sun_up: 0,
      moon_illumination: 11,
      moon_phase: "Waning Crescent",
      moonrise: "05:16 AM",
      moonset: "04:34 PM",
      sunrise: "06:24 AM",
      sunset: "07:18 PM",
    },
    date: "2024-04-06",
    date_epoch: 1712361600,
    day: {
      avghumidity: 42,
      avgtemp_c: 10.1,
      avgtemp_f: 50.2,
      avgvis_km: 10,
      avgvis_miles: 6,
      condition: [Object],
      daily_chance_of_rain: 0,
      daily_chance_of_snow: 0,
      daily_will_it_rain: 0,
      daily_will_it_snow: 0,
      maxtemp_c: 15.6,
      maxtemp_f: 60.1,
      maxwind_kph: 15.1,
      maxwind_mph: 9.4,
      mintemp_c: 4.6,
      mintemp_f: 40.4,
      totalprecip_in: 0,
      totalprecip_mm: 0.01,
      totalsnow_cm: 0,
      uv: 5,
    },
    hour: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
  {
    astro: {
      is_moon_up: 0,
      is_sun_up: 0,
      moon_illumination: 5,
      moon_phase: "Waning Crescent",
      moonrise: "05:42 AM",
      moonset: "05:52 PM",
      sunrise: "06:22 AM",
      sunset: "07:19 PM",
    },
    date: "2024-04-07",
    date_epoch: 1712448000,
    day: {
      avghumidity: 46,
      avgtemp_c: 10.1,
      avgtemp_f: 50.1,
      avgvis_km: 10,
      avgvis_miles: 6,
      condition: [Object],
      daily_chance_of_rain: 0,
      daily_chance_of_snow: 0,
      daily_will_it_rain: 0,
      daily_will_it_snow: 0,
      maxtemp_c: 16.2,
      maxtemp_f: 61.2,
      maxwind_kph: 22.7,
      maxwind_mph: 14.1,
      mintemp_c: 4.5,
      mintemp_f: 40.1,
      totalprecip_in: 0,
      totalprecip_mm: 0,
      totalsnow_cm: 0,
      uv: 6,
    },
    hour: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
  {
    astro: {
      is_moon_up: 0,
      is_sun_up: 0,
      moon_illumination: 1,
      moon_phase: "New Moon",
      moonrise: "06:07 AM",
      moonset: "07:09 PM",
      sunrise: "06:21 AM",
      sunset: "07:20 PM",
    },
    date: "2024-04-08",
    date_epoch: 1712534400,
    day: {
      avghumidity: 64,
      avgtemp_c: 8.3,
      avgtemp_f: 47,
      avgvis_km: 9.3,
      avgvis_miles: 5,
      condition: [Object],
      daily_chance_of_rain: 88,
      daily_chance_of_snow: 0,
      daily_will_it_rain: 1,
      daily_will_it_snow: 0,
      maxtemp_c: 11.9,
      maxtemp_f: 53.5,
      maxwind_kph: 22,
      maxwind_mph: 13.6,
      mintemp_c: 4.4,
      mintemp_f: 39.9,
      totalprecip_in: 0.03,
      totalprecip_mm: 0.67,
      totalsnow_cm: 0,
      uv: 4,
    },
    hour: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
];